### PR TITLE
Pass element index to visitor.

### PR DESCRIPTION
**Pull request by JakeWharton**
@swankjesse @f2prateek

### CODE REVIEW

**Comment by swankjesse** [comment]
I don't understand. This isn't the overall element index; each iteration starts with `0`. I think this would make more sense if we persisted the index.

**Comment by swankjesse** [comment]
(ie. any application that relies on this behavior is probably broken?)

**Comment by JakeWharton** [comment]
The only use case I can think of is when you want to batch. If you want 5 elements, you have to keep your own counter instead of just `return index < 5;`.

**Comment by swankjesse** [comment]
The right solution for batching is to write your own for loops. Especially since there's going to be something you want to do between batches, but not after the last element.

**Comment by JakeWharton** [comment]
We don't offer index-based lookup. There'd be no way to create a batch in an atomic manner unless you used this mechanism with your own counter.

**Comment by swankjesse** [comment]
```
   synchronized (queue) {
     int count = 0;
     while (true) {
       byte[] element = peek();
       if (element == null) break;
       visitor.visit(peek());
       if (++count % 0 == 5) {
         sleep(100);
       }
     }
   }
```

**Comment by swankjesse** [comment]
... after writing that, I think I finally see what I wasn't seeing before. The visitors here don't remove the elements that they visit.

I think we should nuke the visitors completely and replace them with an `Iterator<byte[]>` that can throw a `ConcurrentModificationException`. That would look like this:
```
   synchronized (queue) {
     int count = 0;
     for (byte[] element : queue) {
       visitor.visit(peek());
       queue.remove();
       if (++count % 0 == 5) {
         sleep(100);
       }
     }
   }
```

**Comment by swankjesse** [comment]
(and without the `synchronized` it still works, but we throw a `ConcurrentModificationException` if the queue is ever changes.)

**Comment by JakeWharton** [comment]
Indeed. Works for me. I'm completely contriving all these use cases!

**Comment by JakeWharton** [comment]
@f2prateek might have opinions. He actually uses this thing.

**Comment by swankjesse** [comment]
Yup. I think that an iterator is better than a visitor 'cause the calling code is nicer, you can write your own control flow, and we don't need to introduce a new interface.

**Comment by JakeWharton** [comment]
Yep. The only reason this is a visitor is because we already had one and were changing its functionality.

**Comment by JakeWharton** [comment]
I'm going to :beers:, but I'll make the change later if someone doesn't beat me.

**Comment by f2prateek** [comment]
The Visitor is lazy, so it avoids reading the element, while the iterator would eagerly read the element into a `byte[]`.

**Comment by f2prateek** [comment]
For our very specific use case, we batch elements by size until we exceed a specified amount of bytes. Avoiding reading the element until we choose to would be beneficial.

**Comment by swankjesse** [comment]
It could be an `Iterable<InputStream>` too, though that's more awkward for concurrent modifications. My guess is that a batch that's one-element too large isn't going to be a dealbreaker!

**Comment by JakeWharton** [comment]
We could return objects which have the stream and the length, similar to
TypedInput in Retrofit.

**Comment by swankjesse** [comment]
```
   synchronized (queue) {
     List<byte[]> batch = new ArrayList<>();
     int batchBytes = 0L;
     for (byte[] element : queue) {
       if (batchBytes + element.length > BATCH_LIMIT) {
         sendBatch(batch);
         batch.clear();
         batchBytes = 0L;
       }
       batchBytes += element.length;
       batch.add(element);
     }
   }
   if (!batch.isEmpty()) {
     sendBatch(batch);
   }
```

**Comment by f2prateek** [comment]
`InputStream` wouldn't give us the length of the next element, but true, it's not a dealbreaker. We only need to since users can occasionally send us weird data.

**Comment by JakeWharton** [comment]
You need to call remove(n) after sending a batch and then iteration would
have to start again.

**Comment by swankjesse** [comment]
+1 to remove in bulk.

**Comment by swankjesse** [comment]
(also if you do remove in bulk, then you can `sendBatch()` outside of the `synchronized` block.)

**Pull request closed without merging**
