### PR TITLE
Expose longs from ObjectQueue.

### PR DESCRIPTION
**Pull request by JakeWharton**

### CODE REVIEW

**Comment by f2prateek** [comment]
1) Is it likely there will be more than 2,147,483,647 elements in the queue?

2) Should `QueueFile#size()` also return a long?

**Comment by f2prateek** [comment]
Also should `QueueFile#remove()` accept longs?

**Comment by JakeWharton** [comment]
QueueFile will go `long` in a separate PR but it's much more involved since it requires a change in the on-disk format.

**Comment by f2prateek** [comment]
Ah of course. LGTM

**Comment by JakeWharton** [comment]
We could probably keep `ObjectQueue` with `int`. I don't expect anyone to go over 2^31 elements any time soon.

**Comment by JakeWharton** [comment]
Keeping `int`

**Pull request closed without merging**
