### PR TITLE
Fix file queue to allow clearing empty queue

### PR DESCRIPTION
**Pull request by NightlyNexus**

### CODE REVIEW

**Comment by NightlyNexus** [comment]
This is a failing test.

There are a couple ways I see to fix it, but I figured I'd get opinions on it first.
Should the NoElementException check be removed in QueueFile, or should queueFile.clear() be used by FileObjectQueue?

**Comment by f2prateek** [comment]
interesting, if we want to allow clearing an empty queue, I think the check should remain in QueueFile.remove but moved after the `n == elementCount`check.

I'm not sure that we do want to allow clearing an empty queue though, and the right fix in that case would be to throw an exception in the memory queue implementation.

**Comment by JakeWharton** [comment]
I don't see why clearing an empty queue should fail.

**Comment by NightlyNexus** [comment]
I would think it should be consistent with java.util.Collection.clear.

**Comment by f2prateek** [comment]
Cool so let's move the `isEmpty()` check after the `n == elementCount` check, and this test should pass.

**Comment by NightlyNexus** [comment]
moved the test to check the behavior of QueueFile instead.

**Pull request merged**
