### PR TITLE
WIP: Support files >2GB

### PR DESCRIPTION
**Pull request by JakeWharton**
For review. Haven't done migration or tests yet.

### CODE REVIEW

**Comment by JakeWharton** [comment]
We also optionally could just retain the ability to read/write "V1" formats for legacy files. This just amounts to keeping a `boolean` and changing `writeLong` / `readLong` to secretly only deal with 4 bytes.

Not doing a migration is very appealing to me, but I'm tempted to just rip the bandaid and not maintain two code paths.

**Comment by f2prateek** [comment]
If we release under a `v2` package name, migration can be easy for those who need it.

```java
com.squareup.tape.QueueFile oldQueueFile = ...;
com.squareup.tape.v2.QueueFile newQueueFile = ...;

oldQueueFile.forEach(new ElementReader() {
  @Override public void read(InputStream in, int length) throws IOException {
    byte[] data = new byte[length];
    in.read(data);
    newQueueFile.add(data);
  }
});
```

**Comment by JakeWharton** [comment]
True.

**Comment by swankjesse** [comment]
I think it’s really going to be easier logistically if users don’t need to know that there’s two formats. I’m imagining apps that use Tape and the transition is a lot of work, especially since each app may have many queues.

**Comment by swankjesse** [comment]
Also – rather devastatingly – it’s probably worth the work to make sure Tape 1.x can read Tape 2.x files if possible.

Suppose some team releases an update that upgrades Tape, then rolls it back. Things could get ugly. This is most likely to happen during development & testing when teams switch between different sets of builds.

**Comment by JakeWharton** [comment]
For that I'd like to make QueueFile work in both modes: int and long.
Unless a builder flag is set we'll default new queues to long. There will
also be a static method that takes a from and to file for migration.

Reasonable?

**Pull request closed without merging**
